// footer links
import { FiBriefcase, FiFacebook, FiTwitter, FiLinkedin, FiInstagram, } from "react-icons/fi"

export const footerLinks = {
    "For Job Seekers": [
        { label: "Browse Jobs", href: "/jobs" },
        { label: "Career Advice", href: "/career-advice" },
        { label: "Resume Builder", href: "/resume-builder" },
        { label: "Salary Guide", href: "/salary-guide" },
        { label: "Job Alerts", href: "/job-alerts" },
    ],
    "For Employers": [
        { label: "Post a Job", href: "/post-job" },
        { label: "Browse Resumes", href: "/browse-resumes" },
        { label: "Pricing", href: "/pricing" },
        { label: "Employer Resources", href: "/employer-resources" },
        { label: "Recruitment Solutions", href: "/recruitment-solutions" },
    ],
    Company: [
        { label: "About Us", href: "/about" },
        { label: "Contact Us", href: "/contact" },
        { label: "Careers", href: "/careers" },
        { label: "Press", href: "/press" },
        { label: "Blog", href: "/blog" },
    ],
    Support: [
        { label: "Help Center", href: "/help" },
        { label: "Privacy Policy", href: "/privacy" },
        { label: "Terms of Service", href: "/terms" },
        { label: "Cookie Policy", href: "/cookies" },
        { label: "Sitemap", href: "/sitemap" },
    ],
}

export const socialLinks = [
    { icon: FiFacebook, href: "https://facebook.com", label: "Facebook" },
    { icon: FiTwitter, href: "https://twitter.com", label: "Twitter" },
    { icon: FiLinkedin, href: "https://linkedin.com", label: "LinkedIn" },
    { icon: FiInstagram, href: "https://instagram.com", label: "Instagram" },
]

// featured jobs
export const featuredJobs = [
    {
        id: 1,
        title: "Senior Full Stack Developer",
        company: "TechCorp Inc.",
        location: "San Francisco, CA",
        type: "Full-time",
        salary: "$120k - $160k",
        posted: "2 days ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["React", "Node.js", "TypeScript", "AWS"],
        description: "Join our innovative team to build cutting-edge web applications using modern technologies.",
        featured: true,
    },
    {
        id: 2,
        title: "UX/UI Designer",
        company: "Design Studio Pro",
        location: "Remote",
        type: "Full-time",
        salary: "$80k - $110k",
        posted: "1 day ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["Figma", "Adobe XD", "Prototyping", "User Research"],
        description: "Create beautiful and intuitive user experiences for our diverse client portfolio.",
        featured: true,
    },
    {
        id: 3,
        title: "Data Scientist",
        company: "Analytics Plus",
        location: "New York, NY",
        type: "Full-time",
        salary: "$100k - $140k",
        posted: "3 days ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["Python", "Machine Learning", "SQL", "Tableau"],
        description: "Analyze complex datasets to drive business insights and strategic decisions.",
        featured: false,
    },
    {
        id: 4,
        title: "Product Manager",
        company: "Innovation Labs",
        location: "Austin, TX",
        type: "Full-time",
        salary: "$110k - $150k",
        posted: "1 week ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["Strategy", "Agile", "Analytics", "Leadership"],
        description: "Lead product development from conception to launch in a fast-paced environment.",
        featured: false,
    },
    {
        id: 5,
        title: "DevOps Engineer",
        company: "CloudTech Solutions",
        location: "Seattle, WA",
        type: "Full-time",
        salary: "$95k - $130k",
        posted: "4 days ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["Docker", "Kubernetes", "AWS", "CI/CD"],
        description: "Build and maintain scalable infrastructure for our growing platform.",
        featured: true,
    },
    {
        id: 6,
        title: "Marketing Manager",
        company: "Growth Marketing Co.",
        location: "Los Angeles, CA",
        type: "Full-time",
        salary: "$75k - $100k",
        posted: "5 days ago",
        logo: "/placeholder.svg?height=60&width=60",
        tags: ["Digital Marketing", "SEO", "Content", "Analytics"],
        description: "Drive marketing campaigns and growth strategies for B2B and B2C markets.",
        featured: false,
    },
]

// job categories
export const jobCategories = [
    "All Categories",
    "Technology",
    "Healthcare",
    "Finance",
    "Marketing",
    "Sales",
    "Education",
    "Engineering",
    "Design",
    "Customer Service",
]
// popular
export const popularSearches = [
    "Remote Jobs",
    "Full Stack Developer",
    "Data Scientist",
    "Product Manager",
    "UX Designer",
    "Marketing Manager",
]

// categories
import {
    FiCode, FiHeart, FiDollarSign, FiTrendingUp, FiUsers, FiBookOpen, FiSettings, FiPenTool,
    FiHeadphones, FiShoppingBag, FiTruck, FiHome,
} from "react-icons/fi"
export const categories = [
    {
        id: 1,
        name: "Technology",
        icon: FiCode,
        jobCount: "12,450",
        color: "bg-blue-500",
        bgColor: "bg-blue-50 dark:bg-blue-900/20",
        textColor: "text-blue-600 dark:text-blue-400",
    },
    {
        id: 2,
        name: "Healthcare",
        icon: FiHeart,
        jobCount: "8,230",
        color: "bg-red-500",
        bgColor: "bg-red-50 dark:bg-red-900/20",
        textColor: "text-red-600 dark:text-red-400",
    },
    {
        id: 3,
        name: "Finance",
        icon: FiDollarSign,
        jobCount: "6,780",
        color: "bg-green-500",
        bgColor: "bg-green-50 dark:bg-green-900/20",
        textColor: "text-green-600 dark:text-green-400",
    },
    {
        id: 4,
        name: "Marketing",
        icon: FiTrendingUp,
        jobCount: "5,420",
        color: "bg-purple-500",
        bgColor: "bg-purple-50 dark:bg-purple-900/20",
        textColor: "text-purple-600 dark:text-purple-400",
    },
    {
        id: 5,
        name: "Sales",
        icon: FiUsers,
        jobCount: "7,890",
        color: "bg-orange-500",
        bgColor: "bg-orange-50 dark:bg-orange-900/20",
        textColor: "text-orange-600 dark:text-orange-400",
    },
    {
        id: 6,
        name: "Education",
        icon: FiBookOpen,
        jobCount: "4,560",
        color: "bg-indigo-500",
        bgColor: "bg-indigo-50 dark:bg-indigo-900/20",
        textColor: "text-indigo-600 dark:text-indigo-400",
    },
    {
        id: 7,
        name: "Engineering",
        icon: FiSettings,
        jobCount: "9,120",
        color: "bg-gray-500",
        bgColor: "bg-gray-50 dark:bg-gray-900/20",
        textColor: "text-gray-600 dark:text-gray-400",
    },
    {
        id: 8,
        name: "Design",
        icon: FiPenTool,
        jobCount: "3,890",
        color: "bg-pink-500",
        bgColor: "bg-pink-50 dark:bg-pink-900/20",
        textColor: "text-pink-600 dark:text-pink-400",
    },
    {
        id: 9,
        name: "Customer Service",
        icon: FiHeadphones,
        jobCount: "6,340",
        color: "bg-teal-500",
        bgColor: "bg-teal-50 dark:bg-teal-900/20",
        textColor: "text-teal-600 dark:text-teal-400",
    },
    {
        id: 10,
        name: "Retail",
        icon: FiShoppingBag,
        jobCount: "5,670",
        color: "bg-yellow-500",
        bgColor: "bg-yellow-50 dark:bg-yellow-900/20",
        textColor: "text-yellow-600 dark:text-yellow-400",
    },
    {
        id: 11,
        name: "Logistics",
        icon: FiTruck,
        jobCount: "4,230",
        color: "bg-cyan-500",
        bgColor: "bg-cyan-50 dark:bg-cyan-900/20",
        textColor: "text-cyan-600 dark:text-cyan-400",
    },
    {
        id: 12,
        name: "Real Estate",
        icon: FiHome,
        jobCount: "2,890",
        color: "bg-emerald-500",
        bgColor: "bg-emerald-50 dark:bg-emerald-900/20",
        textColor: "text-emerald-600 dark:text-emerald-400",
    },
]


// testimonials
export const testimonials = [
    {
        id: 1,
        name: "Sarah Johnson",
        role: "Software Engineer",
        company: "TechCorp",
        image: "/placeholder.svg?height=80&width=80",
        rating: 5,
        text: "JobPortal helped me find my dream job in just 2 weeks! The platform is intuitive and the job recommendations were spot-on. I couldn't be happier with my new position.",
        location: "San Francisco, CA",
    },
    {
        id: 2,
        name: "Michael Chen",
        role: "Product Manager",
        company: "Innovation Labs",
        image: "/placeholder.svg?height=80&width=80",
        rating: 5,
        text: "As a hiring manager, JobPortal has been invaluable. The quality of candidates is exceptional, and the platform makes it easy to find the right talent for our team.",
        location: "Austin, TX",
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        role: "UX Designer",
        company: "Design Studio Pro",
        image: "/placeholder.svg?height=80&width=80",
        rating: 5,
        text: "The career resources and job alerts on JobPortal are fantastic. I was able to transition from marketing to UX design with the help of their platform and supportive community.",
        location: "Remote",
    },
    {
        id: 4,
        name: "David Thompson",
        role: "Data Scientist",
        company: "Analytics Plus",
        image: "/placeholder.svg?height=80&width=80",
        rating: 5,
        text: "JobPortal's advanced search filters helped me find exactly what I was looking for. The salary transparency and company reviews made my decision-making process much easier.",
        location: "New York, NY",
    },
]



// industry types
export const industryOptions = [
    "Information Technology (IT)",
    "Software & Web Development",
    "Artificial Intelligence / Machine Learning",
    "Cybersecurity",
    "Telecommunications",
    "E-commerce",
    "Banking & Finance",
    "Accounting & Auditing",
    "Investment & Asset Management",
    "Insurance",
    "Healthcare & Medical",
    "Pharmaceuticals",
    "Biotechnology",
    "Education & E-Learning",
    "Training & Coaching",
    "Engineering & Construction",
    "Architecture & Design",
    "Real Estate",
    "Manufacturing & Production",
    "Automotive",
    "Aerospace & Aviation",
    "Logistics & Transportation",
    "Supply Chain & Procurement",
    "Retail & Wholesale",
    "FMCG (Fast-Moving Consumer Goods)",
    "Hospitality & Tourism",
    "Food & Beverages",
    "Media & Entertainment",
    "Advertising & Marketing",
    "Public Relations",
    "Legal Services",
    "Government & Public Sector",
    "Non-Profit & NGOs",
    "Agriculture & Farming",
    "Textile & Apparel",
    "Energy & Utilities",
    "Oil & Gas",
    "Environmental Services",
    "Mining & Metals",
    "Customer Service & Call Center",
    "Human Resources (HR)",
    "Business Consulting",
    "Event Management",
    "Printing & Publishing",
    "Electronics & Electrical",
    "Security & Surveillance",
    "Marine & Shipping",
    "Fitness & Wellness",
    "Beauty & Personal Care",
    "Data Analytics & Big Data",
    "Blockchain & Cryptocurrency",
    "Gaming & Game Development"
];
